### ISSUE TITLE
hxcfloppyemulator executable should accept filename as argument

### ISSUE THREAD

**Issue by dctucker** [jfdelnero/HxCFloppyEmulator#16]
As I'm fine-tuning my Linux environment, I'm attempting to associate all `.hfe` files with HxC Floppy Emulator so I can quickly open it from my file manager and begin poking around on the floppy image. Unfortunately it seems the executable does not do anything with `argv`/`argc`. This could be a relatively low-effort improvement that may also apply to non-Linux versions of the application.

Expected: `hxcfloppyemulator disk1.hfe` launches the GUI app and automatically loads `disk1.hfe`
Actual: `hxcfloppyemulator disk1.hfe` does the same thing as `hxcfloppyemulator` and just launches the GUI app.

**Comment by jfdelnero** [comment]
sure, you can new download the new version :
https://hxc2001.com/download/floppy_drive_emulator/HxCFloppyEmulator_soft_beta.zip
