### ISSUE TITLE
CLI: Export multiple formats at once

### ISSUE THREAD

**Issue by Sanqui** [jfdelnero/HxCFloppyEmulator#17]
When using the command line interface, it would be useful to enable exporting multiple formats at once, for example with such an interface:

```bash
hxcfe.exe \
 -finput:'20231029_test2-0001/track00.0.hxcstream' \
 -conv:GENERIC_XML -foutput:'floppy.xml' \
 -conv:BMP_IMAGE -foutput:'floppy.bmp'
```

Otherwise it is necessary to run the program multiple times, wasting minutes of time and CPU cycles as the data is re-processed from scratch.

**Comment by jfdelnero** [comment]
Good idea ! I am checking how to implement this.

**Comment by jfdelnero** [comment]
@Sanqui 
This is now implemented. You can test the new version : 
https://hxc2001.com/download/floppy_drive_emulator/HxCFloppyEmulator_soft_beta.zip

**Comment by Sanqui** [comment]
Thank you, I will test it soon!

**Comment by Sanqui** [comment]
Works perfectly, thank you for the prompt feature implementation :+1:
