### ISSUE TITLE
SCP Image with 35 tracks only shows 34 in HxCFloppyEmulator Software

### ISSUE THREAD

**Issue by n6il** [jfdelnero/HxCFloppyEmulator#5]
I used a GreaseWeazle to create a disk image which I knew would have 1 side and and up to 35 tracks.  To make the image I ran:

    gw read --tracks="c=0-34:h=0" fhl_extended_basic.scp

This particular disk has all 35 tracks.  When I loaded the resulting SCP file into the GUI or hxcfe command line tool it only shows 34 tracks instead of 35.   Doing some research about the problem I found the following GreaseWeazle bug report https://github.com/keirf/greaseweazle/issues/277 has a workaround of converting the SCP file to KryoFlux.  I tried this and when I loaded the KryoFlux file into the GUI/hxcfe it now shows all 35 tracks.  Converting to HFE Format also works.

Conversions:

    gw convert --tracks="c=0-34:h=0" fhl_extended_basic.scp my_kf/00.0.raw
    gw convert --tracks="c=0-34:h=0" fhl_extended_basic.scp fhl_extended_basic.hfe::bitrate=250

HxCFloppyEmulator Software Version: 2.14.6.3(Mac)

Attachments in the Zip File:
- fhl_extended_basic.scp
- fhl_extended_basic.hfe (HFE Conversion of the SCP)
- my_kf/  - (KryoFlux conversion of the SCP)
 
[fhl_extended_basic.zip](https://github.com/jfdelnero/HxCFloppyEmulator/files/11428226/fhl_extended_basic.zip)

**Comment by jfdelnero** [comment]
Should now be fixed :

https://hxc2001.com/download/floppy_drive_emulator/HxCFloppyEmulator_soft_beta.zip
v2.14.6.4

Please try again and let me know the result.

Thanks

**Comment by jfdelnero** [comment]
Fixed in v2.14.6.4
