### ISSUE TITLE
Opening CT Raw file with libcapsimage

### ISSUE THREAD

**Issue by FakeShemp** [jfdelnero/HxCFloppyEmulator#6]
When I try to open an old CT Raw file made with Kryoflux Free (the old Amiga program) I get a `Load error! Read file error!`

I can open IPF files just fine so I don't there's an issue with loading the library.

Thank you!

**Comment by jfdelnero** [comment]
The code currently the the file extension to use the libcapsimage  :  *.ipf or *.ct or *.ctr
Does your file have one of these file extensions?

**Comment by FakeShemp** [comment]
Ah, that's the issue then. The file had the `raw` extension. Thanks!
